name: ğŸš€ Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v4
      
      - name: ğŸŸ¢ Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: ğŸ“¦ Install and Build
        run: |
          cd frontend
          npm ci
          npm run build

      - name: ğŸ—œï¸ Compress Build
        run: |
          sudo apt-get update
          sudo apt-get install -y zip
          cd frontend/build
          zip -r ../../deploy.zip .

      - name: ğŸ“ Create Unzip Script
        run: |
          echo "<?php
          \$zip = new ZipArchive;
          if (\$zip->open('deploy.zip') === TRUE) {
              \$zip->extractTo('./');
              \$zip->close();
              echo 'Extraction successful';
          } else {
              echo 'Extraction failed';
              http_response_code(500);
          }
          ?>" > deploy_unzip.php

      - name: ğŸ“‚ Upload Archives via lftp
        run: |
          sudo apt-get install -y lftp
          lftp -e "debug 3; set ftp:ssl-allow no; set ftp:passive-mode on; cd /home/iloveshr/public_html; put deploy.zip; put -O . deploy_unzip.php; quit" -u iloveshr,${{ secrets.FTP_PASSWORD }} ftp.iloveshrigonda.com

      - name: ğŸš€ Trigger Extraction
        run: curl --fail --max-time 300 https://iloveshrigonda.com/deploy_unzip.php

      - name: ğŸ§¹ Cleanup
        run: |
          lftp -e "debug 3; set ftp:ssl-allow no; set ftp:passive-mode on; cd /home/iloveshr/public_html; rm deploy.zip; rm deploy_unzip.php; quit" -u iloveshr,${{ secrets.FTP_PASSWORD }} ftp.iloveshrigonda.com